const BOOK = [
    {
        id: 1,
        title: "Articel 1",
        data: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam gravida pharetra ultricies. Nunc tortor ligula, congue ut quam ac, aliquam gravida nisl. Ut eget lorem auctor, venenatis libero ac, imperdiet risus. Mauris et tristique urna. Sed sit amet nisl eget ex maximus rhoncus eget eu magna. Aliquam erat volutpat. Praesent efficitur ipsum quis ipsum euismod interdum. Suspendisse potenti. Sed euismod quam velit, sit amet accumsan arcu pretium ac. Ut maximus risus id tristique lacinia. Vivamus aliquam cursus magna. Donec enim nibh, congue eu vestibulum eget, pharetra ac purus. Pellentesque consectetur a velit sit amet venenatis. Cras a vulputate dolor. Integer in sem posuere, tincidunt ligula ut, posuere orci.Praesent ex sapien, accumsan auctor rutrum eu, facilisis a neque. Pellentesque ornare eget justo at maximus. Fusce posuere eleifend risus, eget porttitor nisi lacinia quis. Integer pulvinar blandit lacinia. Quisque placerat convallis condimentum. Mauris justo odio, mollis et tempus ac, condimentum id ex. Nam efficitur neque id imperdiet gravida. Sed in sem tincidunt eros consectetur tempor. Quisque leo lacus, consequat sed orci a, lacinia dictum diam. Praesent luctus elit massa, vitae consequat metus luctus ut. In dictum nisi non odio auctor maximus. In hac habitasse platea dictumst. Proin a commodo quam, eget maximus nisi. Nullam auctor neque ac luctus pellentesque. Sed arcu nulla, pellentesque quis eros vitae, condimentum commodo dui. Morbi imperdiet gravida nunc, vel egestas odio tristique a.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur nec orci lectus. Sed vulputate et ante ultrices elementum. Quisque rhoncus fringilla est at condimentum. Integer pharetra tellus egestas quam interdum, sit amet laoreet augue pharetra. Aenean porta dui nulla, id efficitur ante porta eget. Suspendisse convallis lorem vel risus porta, vitae semper neque sodales. Vestibulum eget maximus lacus.",
    },
    {
        id: 2,
        title: "Articel 2",
        data: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam gravida pharetra ultricies. Nunc tortor ligula, congue ut quam ac, aliquam gravida nisl. Ut eget lorem auctor, venenatis libero ac, imperdiet risus. Mauris et tristique urna. Sed sit amet nisl eget ex maximus rhoncus eget eu magna. Aliquam erat volutpat. Praesent efficitur ipsum quis ipsum euismod interdum. Suspendisse potenti. Sed euismod quam velit, sit amet accumsan arcu pretium ac. Ut maximus risus id tristique lacinia. Vivamus aliquam cursus magna. Donec enim nibh, congue eu vestibulum eget, pharetra ac purus. Pellentesque consectetur a velit sit amet venenatis. Cras a vulputate dolor. Integer in sem posuere, tincidunt ligula ut, posuere orci.Praesent ex sapien, accumsan auctor rutrum eu, facilisis a neque. Pellentesque ornare eget justo at maximus. Fusce posuere eleifend risus, eget porttitor nisi lacinia quis. Integer pulvinar blandit lacinia. Quisque placerat convallis condimentum. Mauris justo odio, mollis et tempus ac, condimentum id ex. Nam efficitur neque id imperdiet gravida. Sed in sem tincidunt eros consectetur tempor. Quisque leo lacus, consequat sed orci a, lacinia dictum diam. Praesent luctus elit massa, vitae consequat metus luctus ut. In dictum nisi non odio auctor maximus. In hac habitasse platea dictumst. Proin a commodo quam, eget maximus nisi. Nullam auctor neque ac luctus pellentesque. Sed arcu nulla, pellentesque quis eros vitae, condimentum commodo dui. Morbi imperdiet gravida nunc, vel egestas odio tristique a.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur nec orci lectus. Sed vulputate et ante ultrices elementum. Quisque rhoncus fringilla est at condimentum. Integer pharetra tellus egestas quam interdum, sit amet laoreet augue pharetra. Aenean porta dui nulla, id efficitur ante porta eget. Suspendisse convallis lorem vel risus porta, vitae semper neque sodales. Vestibulum eget maximus lacus.",
    },
    {
        id: 3,
        title: "Articel 3",
        data: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam gravida pharetra ultricies. Nunc tortor ligula, congue ut quam ac, aliquam gravida nisl. Ut eget lorem auctor, venenatis libero ac, imperdiet risus. Mauris et tristique urna. Sed sit amet nisl eget ex maximus rhoncus eget eu magna. Aliquam erat volutpat. Praesent efficitur ipsum quis ipsum euismod interdum. Suspendisse potenti. Sed euismod quam velit, sit amet accumsan arcu pretium ac. Ut maximus risus id tristique lacinia. Vivamus aliquam cursus magna. Donec enim nibh, congue eu vestibulum eget, pharetra ac purus. Pellentesque consectetur a velit sit amet venenatis. Cras a vulputate dolor. Integer in sem posuere, tincidunt ligula ut, posuere orci.Praesent ex sapien, accumsan auctor rutrum eu, facilisis a neque. Pellentesque ornare eget justo at maximus. Fusce posuere eleifend risus, eget porttitor nisi lacinia quis. Integer pulvinar blandit lacinia. Quisque placerat convallis condimentum. Mauris justo odio, mollis et tempus ac, condimentum id ex. Nam efficitur neque id imperdiet gravida. Sed in sem tincidunt eros consectetur tempor. Quisque leo lacus, consequat sed orci a, lacinia dictum diam. Praesent luctus elit massa, vitae consequat metus luctus ut. In dictum nisi non odio auctor maximus. In hac habitasse platea dictumst. Proin a commodo quam, eget maximus nisi. Nullam auctor neque ac luctus pellentesque. Sed arcu nulla, pellentesque quis eros vitae, condimentum commodo dui. Morbi imperdiet gravida nunc, vel egestas odio tristique a.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur nec orci lectus. Sed vulputate et ante ultrices elementum. Quisque rhoncus fringilla est at condimentum. Integer pharetra tellus egestas quam interdum, sit amet laoreet augue pharetra. Aenean porta dui nulla, id efficitur ante porta eget. Suspendisse convallis lorem vel risus porta, vitae semper neque sodales. Vestibulum eget maximus lacus.",
    },
];

export {
    // eslint-disable-next-line import/prefer-default-export
    BOOK,
};
